### DISCUSSION TITLE
multiple temp plotting directories for madmax

### DISCUSSION THREAD

**Discussion by Mearman** [guydavis/machinaris#119] [Q&A] [answered]
Not sure if I'm missing something obvious but it appears only one of my temporary directories is being used now that I've switched to madmax

**Comment by elexx** [comment]
In case you are asking about the ramdisk (-2 parameter of madmax) you need to set `tmp2` in your potter config as your ramdisk, for example
```
directories:
  tmp:
    - /plotting/tmp # SSD
  tmp2: /plotting_ram # RAMDISK
  dst:
    - /plotting/dst # SSD
```

See: https://github.com/guydavis/machinaris/wiki/MadMax#plotman-config
![image](https://user-images.githubusercontent.com/221837/123665946-0bf0d480-d839-11eb-92fc-01c76df82e5b.png)
