### DISCUSSION TITLE
Help! Your harvester appears to be offline!

### DISCUSSION THREAD

**Discussion by FrancescoSaverioZuppichini** [guydavis/machinaris#212] [Q&A] [answered]
Hi guys,

first of all, thank you for this amazing software! So this is what I see from the home page

![image](https://user-images.githubusercontent.com/15908060/127735333-8b07d7b2-e4ec-498d-acce-62304c207dd1.png)

Everything looks good, the worker is plotting 

![image](https://user-images.githubusercontent.com/15908060/127735356-84f0f3a2-56ec-4e29-90a9-e407b2461fb9.png)

but **I don't understand if I also need a harvest**

![image](https://user-images.githubusercontent.com/15908060/127735368-f6c4c4b7-32aa-4ddd-88ea-89115d6cf5a9.png)

I am currently using flexpool but I don't see myself in it, so something is wrong.

Do I need a harvester? If so, how do I create one? I can see that in workers > new I have a UI that generates a docker command/docker-compose config but I don't get it why I need it. 

Thank you!

Cheers,

Francesco

**Comment by guydavis** [comment]
Hi, from the perspective of Chiadog (log monitor) inside the Machinaris container, the "Harvester" is a Chia service/process running.  If just starting with Machinaris, I would recommend deleting the one alert shown, and let everything run for at least 24 hours to see if the problem recurs.  

There is no need to install anything with Machinaris, all the required components are bundled in.  The first install of Machinaris is a "fullnode" because all Chia services are present, including harvester.

If this alert recurs, even after restart, look closely at the debug.log for a cause.  If farming/harvesting is happening, then try [stopping, deleting the debug.log, and restarting](https://github.com/guydavis/machinaris/wiki/FAQ#chiadog-reports-harvester-is-offline).  Sometimes Chiadog incorrectly reports that harvesting is not working, even when it is.   Hope this helps.

**Reply by FrancescoSaverioZuppichini** [reply]
Thank you.

 I let it run for a week, restarted several times and now I see 0 plots (even if they are there) 

![image](https://user-images.githubusercontent.com/15908060/128008622-294af8f4-2e28-4542-92bd-81cc19ca74d0.png)

I have only the default worker and according to the doc it is not an harvester (do I even need one if I am in a pool?). 

**Moreover, it is not clear how to run machinaris and an havester on the same machine since booth container need to bind to the same port.**

I will try to reset everything and I will let you know :) 

Thanks

**Reply by FrancescoSaverioZuppichini** [reply]
I still have the same issue: 

![image](https://user-images.githubusercontent.com/15908060/128017993-96df9e88-5085-4d1b-94ca-0d166e3350b6.png)

My docker-compose file

```yml
version: '3.9' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris 
        container_name: machinaris 
        hostname: minecraft 
        restart: always 
        tty: true 
        volumes: 
            - /home/rage/machinaris:/root/.chia 
            - /media/chia/0/plots:/plots/0 
            - /media/chia/1/plots:/plots/1 
            - /media/chia/2/plots:/plots/2 
            - /media/chia-plotter/plots:/plotting 
        environment: 
            - TZ=Europe/Zurich 
            - mode=fullnode 
            - plots_dir=/plots/0:/plots/1:/plots/2 
            - blockchains=chia,flax 
        ports: 
            - 8926:8926 
            - 8927:8927
            - 8444:8444
            - 8447:8444 
            - 6888:6888
            - 6885:6885
```
