### DISCUSSION TITLE
Farming flax/chives not visible in GUI ?

### DISCUSSION THREAD

**Discussion by Enissay** [guydavis/machinaris#416] [Q&A] [answered]
HI all,

I have an existing wallet with chia, I just moved to machianis (docker-compose) and I want also to farm Flax/Chives...
However, when importing my existing wallet, I do not see any info about the other coins... I do see however that all containers are up and running:
```bash
~$ docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS          PORTS                                                                                                                                                                        NAMES
f93e13bf9b6a   ghcr.io/guydavis/machinaris-flax:latest       "bash ./entrypoint.sh"   52 minutes ago   Up 52 minutes   0.0.0.0:6885->6885/tcp, :::6885->6885/tcp, 8444/tcp, 8447/tcp, 0.0.0.0:6888->6888/tcp, :::6888->6888/tcp, 0.0.0.0:8928->8928/tcp, :::8928->8928/tcp, 8926-8927/tcp           machinaris-flax
b980a3e6d410   ghcr.io/guydavis/machinaris-chives:latest     "bash ./entrypoint.sh"   52 minutes ago   Up 52 minutes   8444/tcp, 8447/tcp, 0.0.0.0:8931->8931/tcp, :::8931->8931/tcp, 0.0.0.0:9647->9647/tcp, :::9647->9647/tcp, 8926-8927/tcp, 0.0.0.0:9699->9699/tcp, :::9699->9699/tcp           machinaris-chives
9a71e9e53ffd   ghcr.io/guydavis/machinaris:latest            "bash ./entrypoint.sh"   52 minutes ago   Up 52 minutes   0.0.0.0:8444->8444/tcp, :::8444->8444/tcp, 0.0.0.0:8447->8447/tcp, :::8447->8447/tcp, 0.0.0.0:8926-8927->8926-8927/tcp, :::8926-8927->8926-8927/tcp                          machinaris
```

What am I missing ? should I crate a new wallet that will be linked to all ?

Here's my main page which is still syncing:
![machinaris_gui_empty](https://user-images.githubusercontent.com/794673/141850701-ffe25fd6-a847-4be3-90d9-1b9a5dfc33ff.png)

Also, it is not detecting any of my existing plots passed to: `plots_dir=/hdd01:/hdd02`. Will it become visible once syncing has finished or something is wrong ?

I am new to machianis, please let me know if any details needed

**Comment by guydavis** [comment]
Welcome!  No, if you followed the [Getting Started guide](https://github.com/guydavis/machinaris/wiki#getting-started) and either [created or imported a key](https://github.com/guydavis/machinaris/wiki/Keys) during Machinaris setup, then the other fork containers will be able to use it.  At this point it looks like you are syncing from scratch the 3 blockchains (Chia, Flax, Chives).  That can take a couple of days.  

Regarding your plots directories, try this from a shell and let me know what you see: 
```
docker exec -it machinaris bash
env | grep -i plots_dir
chia plots show
ls -1 /hdd001 | wc -l
ls -1 /hdd002 | wc -l
```
Also, please confirm for me that you chose to override the default in-container path of  `/plots1`, `/plots2` instead choosing in-container paths of `/hdd001` and `/hdd002`.  Please share with me the exact paths to those volume mounts on your host system.  The easiest way to do this would be to paste the full contents of the docker-compose.yml you generated at [https://www.machinaris.app](https://www.machinaris.app).  Thanks!

**Comment by Enissay** [comment]
@guydavis thank you for the fast reply.
Actually, I have imported my key and I am fine to get a fresh sync.

As of the drives, I found a mistake as I was mounting the drives root folder rather than the subdir which contained the plots. Corrected and relaunched and now all plots are visible.
I confirm also that I am not using the default in-container path of `/plots1`, `/plots2`. Is it fine ? It was easier for me this way to use the same naming for my drives...
It is worth noting as well that I am not plotting on this machine, so both `evo` mounts are not really used (both empty) but I had to fill them else the wizard was not generating the yaml file xD

Here's my `docker-compose.yml` file:

```yaml
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:latest 
        container_name: machinaris 
        hostname: chachacha 
        restart: always 
        volumes: 
            - ~/.machinaris:/root/.chia 
            - "/mnt/evo/chia/temp:/evo_temp" 
            - "/mnt/evo/chia/final:/evo_final" 
            - "/mnt/hdd01/chia_final:/hdd01" 
            - "/mnt/hdd02/chia_final:/hdd02" 
        environment: 
            - TZ=Europe/Brussels 
            - mode=fullnode 
            - worker_address=192.168.1.133 
            - plots_dir=/evo_final:/hdd01:/hdd02
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447 
             
    machinaris-chives: 
        image: ghcr.io/guydavis/machinaris-chives:latest 
        container_name: machinaris-chives 
        hostname: chachacha 
        restart: always 
        volumes: 
            - ~/.machinaris-chives:/root/.chia 
            - ~/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/evo/chia/temp:/evo_temp" 
            - "/mnt/evo/chia/final:/evo_final" 
            - "/mnt/hdd01/chia_final:/hdd01" 
            - "/mnt/hdd02/chia_final:/hdd02" 
        environment: 
            - TZ=Europe/Brussels 
            - mode=fullnode 
            - controller_host=192.168.1.133 
            - worker_address=192.168.1.133 
            - worker_api_port=8931 
            - plots_dir=/evo_final:/hdd01:/hdd02
            - blockchains=chives 
        ports: 
            - 8931:8931 
            - 9699:9699 
            - 9647:9647 
        depends_on: 
            - machinaris 
```

So far, my only remaining question is: Why there's no info about Chives in GUI ?
