### DISCUSSION TITLE
First time installing this. File already exists

### DISCUSSION THREAD

**Discussion by 8PotatoChip8** [guydavis/machinaris#503] [Q&A] [answered]
When trying to install Machinaris docker cannot start the Machinaris compose application. Error: 

> Cannot start Docker Compose application. Reason: Error invoking remote method 'compose-action': Error: Command failed : docker-compose --file "docker-compose.yml" -- project name "machinaris" --project-directory "C:\Machinaris" up -d Container machinaris Starting Error response from daemon: error while creating mounth source path '/run/desktop/mnt/host/c/Disks/Drive 60': mkdir /run/desktop/mnt/host/c/Disks/Drive 60: file exists

![5ioXa3ySZ](https://user-images.githubusercontent.com/73073394/146178237-f4aef584-a807-40e0-9831-998f1d716ae5.png)

I have never used docker before so I am not sure what the problem is. From my understanding of reading the message it is trying to create a file that already exists, but I am confused because I used the machinaris.app website to create the config and I thought it was using preexisting file locations. So I am unsure as to why it is trying to create a file.

I am very new to docker so I am unsure as to what I am needing to post to get help, if you need more info please don't hesitate to ask.
Thanks

**Comment by guydavis** [comment, marked as answer]
Hi, sorry to hear you are encountering this issue with Docker Desktop on Windows.  Please attach the full contents of the `docker-compose.yml` you generated using the [Machinaris site](https://www.machinaris.app).  This will help me better understand the error you received in context. Thanks!

**Reply by 8PotatoChip8** [reply]
Here are the contents of `docker-compose.yml` https://www.toptal.com/developers/hastebin/zebuwaroca.js

**Reply by guydavis** [reply]
Hi, thanks for sharing your `docker-compose.yml`.  Checking on it, I see two issues:

First, the path you are mapping your host mounts to inside the container is the same (`/plots`) for each mount. This is the cause of the error you saw.  It's the Linux equivalent of telling Windows to mount multiple USB drives all as letter D: at the same time.  Conflicts.

![image](https://user-images.githubusercontent.com/12936/146407290-7874540f-1648-4714-afb0-578ef7c73c7e.png)

In the example at https://www.machinaris.app, the "Container Path" is `/plots1` as incrementing is suggested as a way to keep uniqueness.  

However, a more serious problem is that you have so many drives on Windows, you are mounting them as folders (not drive letters).  There is a [known issue](https://github.com/guydavis/machinaris/wiki/Windows) with Docker on Windows that prevents containers such as Machinaris from listing the contents of such volume mounts, making your plots invisible to Machinaris&Chia in the container.  

Here's my suggestion for your docker-compose.yml:
```
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:test 
        container_name: machinaris 
        hostname: jbod1 
        restart: always 
        volumes: 
            - ~/.machinaris:/root/.chia 
       environment: 
            - TZ=America/Toronto 
            - mode=fullnode 
            - worker_address=192.168.2.85
            - remote_shares=//192.168.2.85/Disks:/disks
            - plots_dir=/disks/Drive1:/disks/Drive2:/disks/Drive3:/disks/Drive1 ... :/disks/Drive60 
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447  
```

Some notes:
1. You'll need to share your entire `C:/Disks` folder as a particular user, save the `smbcredentials.txt` in `C:/Users/YOURUSER/.machinaris/` folder as per link above.
2. You'll possibly need to remove the space from all the Drive names so "Drive 1" becomes "Drive1".  I'm not sure if the Linux mount commands will work with those spaces.  Try with the spaces first and check `docker logs -f machinaris` after starting the container.

Hope this helps and let me know how it goes!
