### DISCUSSION TITLE
Instructions for Drive feature setup

### DISCUSSION THREAD

**Discussion by hutchwilco** [guydavis/machinaris#643] [Q&A]
Hey Guy!

Just a note to request a little more context for the yaml addition for enabling the Drive feature for Docker-Compose users:

The yaml sample shown doesn't show where that should be nested ( if at all ) within the existing docker-compose yaml.
I tried to put it in with the indents that it has in the example, specifically:
```
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdb:/dev/sdb
```
but I got this error:
`ERROR: In file './docker-compose.yml', service 'cap_add' must be a mapping not an array.`

I've tried to indent it so that it's nested under the 'machinaris:' as below, but this doesn't work (but doesn't give an error).
Could you clarify where this should be nested/indented?
Thanks!

```
services:
    machinaris:
        image: ghcr.io/guydavis/machinaris

```
...
```
        ports:
            - 8926:8926
            - 8927:8927
            - 8444:8444
            - 8447:8447
        cap_add:
            - SYS_RAWIO
        devices:
            - /dev/sda:/dev/sda
            - /dev/sdaa:/dev/sdaa
            - /dev/sdab:/dev/sdab
            - /dev/sdac:/dev/sdac
```
...
