### DISCUSSION TITLE
Selecting *for* alert types, and other alert questions

### DISCUSSION THREAD

**Discussion by hutchwilco** [guydavis/machinaris#689] [Q&A]
Hi, I see we have in 0.7.2 an ignore feature.
Is it possible to get an include feature? 

Use case: Currently I use pushover and get the daily summary. 
I don't get the high priority message when one of my harvesters is offline though.

I can't see a way in the alerts config to achieve this.
My relevant alerts config:
```
...
daily_stats:
  enable: true
  time_of_day: 20
...
 pushover:
    enable: true
    daily_stats: true
    wallet_events: false
    credentials:
...
```

and the type of alert I'd like to get:

`chiaharvester2 | chia | HARVESTER | Your harvester appears to be offline! No events for the past 31401 seconds. | 2022-06-08 20:43 | HIGH
`
Having written this out, I'm not sure why I'm *not* getting the harvester down alert.
Also wondering if you could explain what a "consumer" is in the the context of the alerts config for a multi-harvester setup.

Thanks!

**Comment by guydavis** [comment]
Good suggestion.  I've just enhanced the alert mechanism to also support the `allow` keyword in [Chiadog configuration](https://github.com/guydavis/machinaris/wiki/ChiaDog#ignore-alerts).  This selectively includes only specified events for a particular notifier on a particular worker. Available now in Machinaris `:develop` images.  Please give it a try and let me know.

**Reply by hutchwilco** [reply]
Cool, thanks @guydavis!

I tried your enhancement, and I haven't managed to get "harvester down" notifications. Perhaps I've done something wrong:

I updated my fullnode to 0.7.3 using the `:develop` image.
I then updated the alerts config for the fullnode like so:

```
notifier:
  pushover:
    enable: true
    daily_stats: true
    wallet_events: false
    credentials:
      api_token: 'MYSECRET'
      user_key: 'MYOTHERSECRET'
    allow:
      service: 'harvester'
```

I then unplugged the network connection to one of my harvesters, but didn't see any alerts in the Machinaris Alerts tab or on my Pushover client.

Looking at the alerts log, I did see the following for the fullnode:
[Chiadoglog.txt](https://github.com/guydavis/machinaris/files/8913384/Chiadoglog.txt)
 
including:
`Skip non-allowed Pushcut notificiation for event:  (pushover_notifier.py:29)`

Which seems odd as I don't use Pushcut. The fullnode alerts log is now just full of that message.
