### DISCUSSION TITLE
Version 2.0.0

### DISCUSSION THREAD

**Discussion by guydavis** [guydavis/machinaris#920] [Announcements]
### Added
 - Request a new plot check, via 'Recheck' button added to Check results dialog on Farming page.  
 - Optionally exclude certain plot directories from replotting check to free disk space. Useful for drives only partially dedicated to holding plots.
### Changed
 - Deprecated stale blockchains, by hiding them from Worker wizards: BPX, N-Chain, Silicoin, Stor
### Updated
 - [Bladebit](https://github.com/Chia-Network/bladebit/releases/tag/v3.0.0) to 3.0.0.
 - [Cactus](https://github.com/Cactus-Network/cactus-blockchain/releases/tag/2.0.0) to v2.0.0
 - [Chia](https://github.com/Chia-Network/chia-blockchain/releases/tag/2.0.0) to v2.0.0.
 - [Gigahorse](https://github.com/madMAx43v3r/chia-gigahorse/releases/tag/v1.8.1.giga14) to v1.8.1.giga14.
 - [HDDCoin](https://github.com/HDDcoin-Network/hddcoin-blockchain/releases/tag/3.0.0) to 3.0.0 based on Chia 1.8.2.
 - [MMX](https://github.com/madMAx43v3r/mmx-node/releases/tag/v0.10.6) to v0.10.6. 
 - [Wheat](https://github.com/wheatnetwork/wheat-blockchain/releases/tag/1.8.2) to v1.8.2.

<hr /><em>This discussion was created from the release <a href='https://github.com/guydavis/machinaris/releases/tag/2.0.0'>Version 2.0.0</a>.</em>

**Comment by bclaasssen** [comment]
Chia seems not getting updated to 2.0.0. Also there is another update availible.

**Reply by guydavis** [reply]
Hi, on Unraid? If so, try a Force Update in the Advanced View od Unraid UI Docker tab. Unraid regularly fails to find the most recent image, instead using a months old locally cached version.

Regarding Chia 2.0.1, the bad plots error they had in their 2.0.0 GUI (and CLI) never affected Machinaris v2.0.0 as I specifically avoided the broken commands.  Thaks for the feedback.

**Reply by bclaasssen** [reply]
Hi,
Thank you for the response and your great work!
I'm not using UnRaid, i'm on Ubuntu 20

i've updated ubuntu and then deleted all docker images and containers, then
`docker compose pull && docker compose up -d --force-recreate`

![image](https://github.com/guydavis/machinaris/assets/20355556/a9dd0dbb-e492-40bf-9585-75e8df543945)

The errors on the right are translated:
* Worker clock difference with controler
This has allways been there, haven't got this to fix this. But thats another story.
* Machinaris version not the same as controller
Might be related?

Chia is stuck at height 4187809. I've noticed im not the only one. I guess this is related to the chia update.

**Reply by guydavis** [reply]
Alright, thanks for sharing more details of your bug report such as platform.  Here are the complete steps to [perform an upgrade](https://github.com/guydavis/machinaris/wiki/Linux#upgrade):
![image](https://github.com/guydavis/machinaris/assets/12936/b6d34967-d833-4894-952a-75e283963eb4)
Please be sure to execute all the steps to complete the upgrade properly.

Also, I would suggest you look at your timezone configurations on all worker systems.  I hope they are the same and your computer clocks are correct.  

Example of the TZ environment variable which is automatically set when you build a `docker-compose.yml` at https://www.machinaris.app
![image](https://github.com/guydavis/machinaris/assets/12936/655722cc-08a5-450f-b607-a6ff1c570305)

Hope this helps.

**Reply by bclaasssen** [reply]
Thanks for helping me out!

I followed the instructions, but i'm afraid the steps didn't help.
I'm running on a Rock-Pi 4B. Could it have anything to do with ARM chia repository?

cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Armbian 23.02.2 Focal"
```

docker-compose.yml 
```
`version: '3.7'
services:
    machinaris:
        image: ghcr.io/guydavis/machinaris:latest
        container_name: machinaris
        hostname: rockpi-4b
        restart: always
        volumes:
            - "/mnt/ssd/chia:/root/.chia"
            - "/mnt/CF01-6TB:/plots1"
            - "/mnt/CF02-6TB:/plots2"
            - ...
            - environment:
            - TZ=Europe/Amsterdam
            - mode=fullnode
            - worker_address=192.168.0.152
            - plots_dir=/plots1:/plots2:/plots3:/plots4:/plots5:/plots6:/plots7:/plots8:/plots9:/plots10:/plots11:/plots12:/plots13:/plots14:/plots15:/plots17:/plots18:/plots19:/plots20:/plots21:/plots22:/plots23:/plots24:/plots25:/plots26:/plots27:/plots28:/plots29:/plots30:/plots31:/plots32
            - blockchains=chia
        ports:
            - 8926:8926
            - 8927:8927
            - 8444:8444
            - 8447:8447
        cap_add:
            - SYS_RAWIO
        devices:
            - /dev/sda:/dev/sda
            - ...
`
```

docker logs machinaris

```
Welcome to Machinaris v2.0.0!
chia - fullnode on aarch64
Configuring Chia...
Adding key #0 at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1,
....
Daemon not started yet
Starting daemon
chia_harvester: started
chia_farmer: started
chia_full_node: started
chia_wallet: started
Configuring Plotman...
Starting Machinaris API server...
Starting Machinaris Web server...
Completed startup.  Browse to port 8926.
```

![image](https://github.com/guydavis/machinaris/assets/20355556/6702bd9a-7d04-4181-b942-e06ab57ae179)

Many thanks in advance

**Reply by guydavis** [reply]
Thanks for sharing other pertinent details about your deployment such as platform being ARM64.  Yes, there are [known issues](https://github.com/guydavis/machinaris/wiki/RaspberryPiOS#known-issues) on that platform.  I don't run on it so you many want to check in the Discord for community support from others using it.

**Reply by bclaasssen** [reply]
Thank you sir. 
I noticed a difference in the chia action files:
```
        uses: docker/build-push-action@v4
        with:
          file: docker/dockerfile
          context: .
          platforms: linux/amd64
```

```
uses: docker/build-push-action@v4
        with:
          file: docker/dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
```
