### ISSUE TITLE
"Alerts: Recent Notifications" does not show new entries detected by Chiadog

### ISSUE THREAD

**Issue by okkar** [guydavis/machinaris#168]
**Describe the bug**
"Alerts - Recent Notifications" page is not showing the latest alerts.

**To Reproduce**

1. Configure alerts for Chia.
2. Run the farmer as usual.
3. Alerts that should appear on "Recent Notifications" page do not appear. (e.g. "Found 1 proof(s)!")

**Expected behavior**

"Recent Notifications" should refresh with important updates in "View Chia Monitoring Logs".

**System setup:**
 - OS: Ubuntu
 - Docker version number: 20.10.7
 - Machinaris branch: main
 - Machinaris version number: 0.5.0

**Config**
<details><summary>full configuration</summary>

```
# paste your Docker run or Docker compose here
{
    "AppArmorProfile": "docker-default",
    "Args": [
        "./entrypoint.sh"
    ],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "bash",
            "./entrypoint.sh"
        ],
        "Env": [
            "API_SETTINGS_FILE=/root/.chia/machinaris/config/api.cfg",
            "AUTO_PLOT=false",
            "controller_api_port=8927",
            "controller_host=localhost",
            "controller_web_port=8926",
            "farmer_address=null",
            "farmer_pk=null",
            "farmer_port=8447",
            "FLASK_APP=/machinaris/main.py",
            "FLASK_ENV=production",
            "keys=/root/.chia/mnemonic.txt",
            "mode=fullnode",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/chia-blockchain/venv/bin",
            "plots_dir=/plots/plots-dst:/plots/ds1815-chia-plots-volume1:/plots/ds1815-chia-plots-volume2:/plots/ds1815-chia-plots-volume3:/plots/farm/hdd01:/plots/farm/hdd02:/plots/farm/hdd03:/plots/farm/hdd04",
            "pool_pk=null",
            "testnet=false",
            "TZ=Asia/Singapore",
            "WEB_SETTINGS_FILE=/root/.chia/machinaris/config/web.cfg",
            "XDG_CONFIG_HOME=/root/.chia",
            "blockchains=chia,flax",
            "pool_contract_address=null",
            "flax_farmer_port=6885"
        ],
        "ExposedPorts": {
            "6885/tcp": {},
            "6888/tcp": {},
            "8444/tcp": {},
            "8447/tcp": {},
            "8555/tcp": {},
            "8926/tcp": {},
            "8927/tcp": {}
        },
        "Hostname": "ubuntu",
        "Image": "ghcr.io/guydavis/machinaris",
        "Labels": {},
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/id_rsa": {},
            "/plots/ds1815-chia-plots-volume1": {},
            "/plots/ds1815-chia-plots-volume2": {},
            "/plots/ds1815-chia-plots-volume3": {},
            "/plots/farm": {},
            "/plots/plots-dst": {},
            "/plotting": {},
            "/root/.chia": {}
        },
        "WorkingDir": "/chia-blockchain"
    },
    "Created": "2021-07-10T02:30:45.942349522Z",
    "Driver": "overlay2",
    "ExecIDs": [
        "26cfe6381826d674065d12a24310143577472030cec83092be6bba929236a9a5",
        "0aae308167738ebdedc9d481b3b3ce6c174d2acac23025f66f9d60327075d06c",
        "8dde1167874b33fefd8c595178a494888b7eb19a49e92c465d3c0847aaf9b688",
        "b5d1844f6d13c8edc72ab3ce864f30813e496b8ceed66da2867f44dac02f4944",
        "8d6b274d2ece51cd389962992f7b6d459763de72750f32df8d99e6d94184c2db",
        "06d9dac7318d16e7be66d02046196cc0b8b35bf6c8e52ded2830117fd8330f7e",
        "bdbd2d755e80f61dc9bb82f3f047b987d6e3a87ca4616c06d27ab0642e7d493e"
    ],
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/ee5031987020dee913401228809b900ee93cdd0742673d7f7363bc61da972b9c-init/diff:/var/lib/docker/overlay2/ac153b4e5b62556d95c8f5f442eda013c33256f1b033e14d14dca4df8f8080f2/diff:/var/lib/docker/overlay2/799f34802999626e6897bc4cc8de7ef01851e7463783b894d60a0d4912cee8dc/diff:/var/lib/docker/overlay2/bdb60e86fb85fb6cf3989d91ccfe51855e7abce15fa41109929be5c30915b297/diff:/var/lib/docker/overlay2/bd77b553a507824b8a022b463b8f0e03b6389e338ea39ee9d304e613d6e82050/diff:/var/lib/docker/overlay2/2656b78d6eee7c42ed466df3cb578756696e57060b10f611d76e9d00229c1bcf/diff",
            "MergedDir": "/var/lib/docker/overlay2/ee5031987020dee913401228809b900ee93cdd0742673d7f7363bc61da972b9c/merged",
            "UpperDir": "/var/lib/docker/overlay2/ee5031987020dee913401228809b900ee93cdd0742673d7f7363bc61da972b9c/diff",
            "WorkDir": "/var/lib/docker/overlay2/ee5031987020dee913401228809b900ee93cdd0742673d7f7363bc61da972b9c/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/mnt/ds1815-chia-plots-volume2:/plots/ds1815-chia-plots-volume2",
            "/mnt/ds1815-chia-plots-volume3:/plots/ds1815-chia-plots-volume3",
            "/home/okkar/plots-dst:/plots/plots-dst",
            "/mnt/ssd:/plotting",
            "4111d542f0b7f33d3e0580758f4bddaa1185c11eb98328e3142cc448ec641b8f:/id_rsa",
            "/home/okkar/.machinaris:/root/.chia",
            "/mnt/ds1815-chia-plots-volume1:/plots/ds1815-chia-plots-volume1",
            "/mnt/farm:/plots/farm"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "6885/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "6885"
                }
            ],
            "6888/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "6888"
                }
            ],
            "8444/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8444"
                }
            ],
            "8447/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8447"
                }
            ],
            "8926/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8926"
                }
            ],
            "8927/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8927"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023/hostname",
    "HostsPath": "/var/lib/docker/containers/a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023/hosts",
    "Id": "a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023",
    "Image": "sha256:1c6cfe82a80bafd6160c7be7770741e6d7f74824af8ee49854310cbff759bcf5",
    "LogPath": "/var/lib/docker/containers/a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023/a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/plots/farm",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/farm",
            "Type": "bind"
        },
        {
            "Destination": "/plots/ds1815-chia-plots-volume2",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/ds1815-chia-plots-volume2",
            "Type": "bind"
        },
        {
            "Destination": "/plots/ds1815-chia-plots-volume3",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/ds1815-chia-plots-volume3",
            "Type": "bind"
        },
        {
            "Destination": "/plots/plots-dst",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/home/okkar/plots-dst",
            "Type": "bind"
        },
        {
            "Destination": "/plotting",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/ssd",
            "Type": "bind"
        },
        {
            "Destination": "/id_rsa",
            "Driver": "local",
            "Mode": "z",
            "Name": "4111d542f0b7f33d3e0580758f4bddaa1185c11eb98328e3142cc448ec641b8f",
            "Propagation": "",
            "RW": true,
            "Source": "/var/lib/docker/volumes/4111d542f0b7f33d3e0580758f4bddaa1185c11eb98328e3142cc448ec641b8f/_data",
            "Type": "volume"
        },
        {
            "Destination": "/root/.chia",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/home/okkar/.machinaris",
            "Type": "bind"
        },
        {
            "Destination": "/plots/ds1815-chia-plots-volume1",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/ds1815-chia-plots-volume1",
            "Type": "bind"
        }
    ],
    "Name": "/machinaris",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "b112ed3a91947cd2a30dc2fb70af026c82f8ee31f7f0b11eec405d242abcbb9a",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:02",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "b112ed3a91947cd2a30dc2fb70af026c82f8ee31f7f0b11eec405d242abcbb9a",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "172.17.0.2",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:02",
                "NetworkID": "8cce9bd5b8e8786128378f3528d3e43a9fbda80b95e573b8484815c448780305"
            }
        },
        "Ports": {
            "6885/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "6885"
                },
                {
                    "HostIp": "::",
                    "HostPort": "6885"
                }
            ],
            "6888/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "6888"
                },
                {
                    "HostIp": "::",
                    "HostPort": "6888"
                }
            ],
            "8444/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8444"
                },
                {
                    "HostIp": "::",
                    "HostPort": "8444"
                }
            ],
            "8447/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8447"
                },
                {
                    "HostIp": "::",
                    "HostPort": "8447"
                }
            ],
            "8555/tcp": null,
            "8926/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8926"
                },
                {
                    "HostIp": "::",
                    "HostPort": "8926"
                }
            ],
            "8927/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8927"
                },
                {
                    "HostIp": "::",
                    "HostPort": "8927"
                }
            ]
        },
        "SandboxID": "c1f7b65fd5c33e8b9fd981efd8ddbd19de896cf3eeebf13c7c4ded2f73f7ec63",
        "SandboxKey": "/var/run/docker/netns/c1f7b65fd5c3",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "bash",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 4,
            "ResourceId": "a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/a6d597236585b81844d9e490ea5c554dd295e608b158fe289ecebf3dc04c5023/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 2944975,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2021-07-10T02:30:46.295642474Z",
        "Status": "running"
    }
}
```

</details>

**Additional context & screenshots**
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/3801075/125171006-6ba99100-e1e4-11eb-9ecd-4c480bb0aad4.png">

**Comment by guydavis** [comment]
Hi, thanks for the detailed report.  First off, please try to restart the Machinaris container and see if the issue recurs.

Then please attach your Settings | Alerts config contents to this issue.  Feel free to redact any private information.

Finally, please attach your /home/okkar/.machinaris/machinaris/logs/apisrv.log file.  Perhaps there are errors within.

Thanks!

**Comment by okkar** [comment]
Issue persists after container restart and container recreation.


<details><summary>Alerts configuration</summary>

```
# This is useful to differentiate multiple chiadog
# instances monitoring multiple harvesters
notification_title_prefix: 'ubuntu-Chia'
log_level: INFO

# Only one consumer can be enabled at a time, you can
# delete the section for the consumer which you aren't using
# DON'T CHANGE file_path IT'S ALREADY SET IN-CONTAINER FOR MACHINARIS!
chia_logs:
  file_log_consumer:
    enable: true
    file_path: '/root/.chia/mainnet/log/debug.log'
  #network_log_consumer:
  #  enable: false
  #  remote_file_path: '~/.chia/mainnet/log/debug.log'
  #  remote_host: 192.168.0.100
  #  remote_user: chia
  #  remote_port: 22

# Enable this and chiadog will ping a remote server every 5 minutes
# That way you can know that the monitoring is running as expected
#keep_alive_monitor:
#  enable_remote_ping: false
#  ping_url: ''

# Enable this and you'll receive a daily summary notification
# on your farm performance at the specified time of the day.
daily_stats:
  enable: true
  time_of_day: 21

# We support a lot of notifiers, please check the README for more
# information. You can delete the sections which you aren't using.
# You can also enable more than one notifier and send different
# notifications to each of them. E.g. enable daily_stats only to E-mail.
# If you enable wallet_events you'll get notifications anytime your
# wallet receives some XCH (e.g. farming reward).
notifier:
  pushover:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      api_token: 'dummy_token'
      user_key: 'dummy_key'
  telegram:
    enable: true
    daily_stats: true
    wallet_events: true
    credentials:
      bot_token: 'xxxREDACTEDxxx'
      chat_id: 'xxxREDACTEDxxx'
  smtp:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      sender: 'chia@example.com'
      sender_name: 'chiadog'
      recipient: 'you@example.com'
      username_smtp: 'username'
      password_smtp: 'password'
      host: 'smtp.example.com'
      port: 587
  script:
    # DON'T CHANGE THIS SCRIPT NOTIFIER, IT'S USED BY MACHINARIS!
    enable: true
    daily_stats: true
    wallet_events: true
    script_path: '/root/.chia/chiadog/notifier.sh'
  discord:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      webhook_url: 'https://discord.com/api/webhooks/...'
  slack:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
     webhook_url: 'https://hooks.slack.com/services/...'
  mqtt:
    enable: false
    daily_stats: true
    wallet_events: true
    topic: chia/chiadog/alert
    qos: 1
    retain: false
    credentials:
      host: '192.168.0.10'
      port: 8883
      username: ''
      password: ''
```
</details>

<details><summary>apisrv.log content</summary>

```
[2021-07-11 23:29:29 +0800] [1975] [INFO] Starting gunicorn 20.1.0
[2021-07-11 23:29:29 +0800] [1975] [INFO] Listening at: http://0.0.0.0:8927 (1975)
[2021-07-11 23:29:29 +0800] [1975] [INFO] Using worker: sync
[2021-07-11 23:29:29 +0800] [2184] [INFO] Booting worker with pid: 2184
[2021-07-11 23:29:29 +0800] [2185] [INFO] Booting worker with pid: 2185
[2021-07-11 23:30:48 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:31:05 +0800] [2184] [INFO] Starting archiver run...
[2021-07-11 23:31:05 +0800] [2184] [INFO] About to start archiver...
[2021-07-11 23:31:05 +0800] [2184] [INFO] Completed launch of archiver.
[2021-07-11 23:31:25 +0800] [2184] [INFO] Starting Plotman run...
[2021-07-11 23:31:26 +0800] [2184] [INFO] No running plot jobs found so deleting /plotting/*.tmp before starting plotman.
[2021-07-11 23:31:26 +0800] [2184] [INFO] Completed launch of plotman.
[2021-07-11 23:32:15 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:33:33 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:34:53 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:36:05 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:37:17 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:38:39 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
[2021-07-11 23:40:01 +0800] [1975] [INFO] Skipping non-plot file named: /plots/farm/hdd04/._config.yaml
```

</details>
