### ISSUE TITLE
Unable to plot since new update

### ISSUE THREAD

**Issue by ApfelBirneKreis** [guydavis/machinaris#259]
When i try to plot over the gui this error message occours:

![image](https://user-images.githubusercontent.com/84158946/131399877-723a68d5-6591-40d1-a007-f3cb896cd058.png)

Plotting over cli with this command works fine:

`chia_plot -n 100 -r 16 -u 256 -t /plotting/ -d /plots1/ -f xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -c xchxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

Im using machinaris with Unraid 6.9.2 in the Machinaris Docker container. 
Tried the `:latest` and `:test` branch. Both spit out the same issue.

**Comment by guydavis** [comment]
Hi, how are you starting the Machinaris container?  As per the Github bug template, please provide Windows/Linux/MacOS, etc.

**Comment by ApfelBirneKreis** [comment]
**Describe the bug**


**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Start machinaris via the Unraid GUI
2. Go to Plotting page 
3. Start plotting via the "Start Plotting" button
4. See error
5. It also happens when you try to change Plotting settings in the settings menue. Same plotman error occours

**Expected behavior**


**System setup:**
 - OS: Unraid 6.9.2
 - Docker version number (output of `v4.20.1`)
 - Machinaris branch: :test , :latest
 - Machinaris version number: 0.5.4

**Config**
Plotting Config:

```
# Learn more about Plotman at https://github.com/ericaltendorf/plotman
# https://github.com/ericaltendorf/plotman/wiki/Configuration#versions
version: [2]

logging:
        # DO NOT CHANGE THIS IN-CONTAINER PATH USED BY MACHINARIS!
        plots: /root/.chia/plotman/logs

user_interface:
        use_stty_size: False

commands:
        interactive:
                autostart_plotting: False
                autostart_archiving: False
  
# Where to plot and log.
directories:

        # One or more directories to use as tmp dirs for plotting.  The
        # scheduler will use all of them and distribute jobs among them.
        # It assumes that IO is independent for each one (i.e., that each
        # one is on a different physical device).
        #
        # If multiple directories share a common prefix, reports will
        # abbreviate and show just the uniquely identifying suffix.
        # REMEMBER ALL PATHS ARE IN-CONTAINER, THEY MAP TO HOST PATHS
        tmp:
                - /plotting

        # Optional: tmp2 directory.  If specified, will be passed to
        # the chia and madmax plotters as the '-2' param.
        tmp2:
                 - /plotting2

        # One or more directories; the scheduler will use all of them.
        # These again are presumed to be on independent physical devices,
        # so writes (plot jobs) and reads (archivals) can be scheduled
        # to minimize IO contention.
        # REMEMBER ALL PATHS ARE IN-CONTAINER, THEY MAP TO HOST PATHS
        dst:
                - /plots1

# See: https://github.com/guydavis/machinaris/wiki/Plotman#archiving
#archiving:
        #target: rsyncd
        #env:
                #site_root: /mnt/disks
                #user: root
                #host: aragorn
                #rsync_port: 12000
                #site: disks

# Plotting scheduling parameters
scheduling:
        # Run a job on a particular temp dir only if the number of existing jobs
        # before tmpdir_stagger_phase_major tmpdir_stagger_phase_minor
        # is less than tmpdir_stagger_phase_limit.
        # Phase major corresponds to the plot phase, phase minor corresponds to
        # the table or table pair in sequence, phase limit corresponds to
        # the number of plots allowed before [phase major, phase minor]
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 1
        # Optional: default is 1
        tmpdir_stagger_phase_limit: 1

        # Don't run more than this many jobs at a time on a single temp dir.
        # Increase for staggered plotting by chia, leave at 1 for madmax sequential plotting
        tmpdir_max_jobs: 1

        # Don't run more than this many jobs at a time in total.
        # Increase for staggered plotting by chia, leave at 1 for madmax sequential plotting
        global_max_jobs: 1 

        # Don't run any jobs (across all temp dirs) more often than this, in minutes.
        global_stagger_m: 30

        # How often the daemon wakes to consider starting a new plot job, in seconds.
        polling_time_s: 20

        # Optional: Allows overriding some characteristics of certain tmp
        # directories. This contains a map of tmp directory names to
        # attributes. If a tmp directory and attribute is not listed here,
        # it uses the default attribute setting from the main configuration.
        #
        # Currently support override parameters:
        #     - tmpdir_max_jobs
        #tmp_overrides:
                # In this example, /plotting3 is larger than the other tmp
                # dirs and it can hold more plots than the default.
                #/plotting3:
                #        tmpdir_max_jobs: 5

# Configure the plotter.  See: https://github.com/guydavis/machinaris/wiki/Plotman#plotting
plotting:
        # See Keys page, for 'Farmer public key' value
        farmer_pk: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        # ONLY FOR OLD SOLO PLOTS, COMMENT OUT IF PORTABLE PLOTTING!!!
        #pool_pk: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        # See 'Settings | Pools' page, for 'Pool contract address' value, UNCOMMENT IF PORTABLE PLOTTING!!!
        pool_contract_address: xchxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        # If you enable 'chia', plot in *parallel* with higher tmpdir_max_jobs and global_max_jobs
        # If you enable 'madmax', plot in *sequence* with very low tmpdir_max_jobs and global_max_jobs
        type: madmax

        chia:
                # The stock plotter: https://github.com/Chia-Network/chia-blockchain
                k: 32                # k-size of plot, leave at 32 most of the time
                e: False             # Disable bitfield back sorting (default is True) 
                n_threads: 2         # Threads per job
                n_buckets: 128       # Number of buckets to split data into
                job_buffer: 3389     # Per job memory

        madmax:
                # madMAx plotter: https://github.com/madMAx43v3r/chia-plotter
                n_threads: 16          # Default is 4, SLOWLY crank up if you have many cores
                n_buckets: 256        # Default is 256
                n_buckets3: 256       # Default is 256
                n_rmulti2: 1          # Default is 1 

```

Docker Run:
Sice i use the Machinaris Unraid app i don´t have acces to docker run



**Additional context & screenshots**
https://user-images.githubusercontent.com/84158946/131399877-723a68d5-6591-40d1-a007-f3cb896cd058.png
