### ISSUE TITLE
make machinaris robust against misconfigurations

### ISSUE THREAD

**Issue by HitLuca** [guydavis/machinaris#343]
I recently migrated to machinaris 0.6.0, and tried to keep the whole flax blockchain files by following the `
How do I update from v0.5.x to v0.6.0+ with Fork support?` guide on the project wiki. I managed to screw something up but nothing major, after a couple of fixes everything started working as expected. 

I am running all the forks except chives, as it needs different plots

I am now seeing some weird entries on the machinaris web interface, which I presume are coming from the main controller adding information about the initial (wrong) services I spun up, and not cleaning the services state after I fixed them. The issues I am facing are:

- `farming` page, workers tab, instead of seeing one single `Daily Summary` + disk usage graph, I am seeing this
![image](https://user-images.githubusercontent.com/7645621/137881600-36f99095-f7aa-4c60-ae2e-885ee033829e.png)
I also see some related console errors 
![image](https://user-images.githubusercontent.com/7645621/137881690-997e7612-9f0f-4641-a1bf-1731c49e4de0.png)

- `wallet` page, seeing duplicated wallets and a missing one, but at the time I took the screenshot the new forks are still syncing so that may be related
![image](https://user-images.githubusercontent.com/7645621/137882057-4c9db4df-a990-4ca1-98a5-b2d94a93b790.png)
I also don't have a `controller-hddcoin` entry, but again that may be related to the fork syncing

- `blockchains` page, I am seeing double `chia` and double `flax` tabs, the flax one in particular has an error related to a missing `config.yaml` file (which is there after checking)
![image](https://user-images.githubusercontent.com/7645621/137882420-c3b045c5-1366-4020-84c1-59bf6bf50e86.png)
![image](https://user-images.githubusercontent.com/7645621/137882445-3dfa7b09-ba58-4cd1-b0be-6954b5ccf395.png)

- `connections` page, I get an error message, but the various entries look good
![image](https://user-images.githubusercontent.com/7645621/137882645-ab429382-c025-4621-b4c6-55022d698b7b.png)

- `pools` page, seeing two entries of the same thing? Not sure this is an error
![image](https://user-images.githubusercontent.com/7645621/137882760-b939a9be-c506-444c-a759-012c549faf82.png)
  
- `settings` page (`alerts`, `farming` `plotting`), under `worker` I can see all my workers, but under `fork` I can only see the `nchain` fork
![image](https://user-images.githubusercontent.com/7645621/137883133-af705eb3-c9ae-46aa-a10a-b2b43b0d0713.png)

- `settings` page, `pools` section, I see the same pool info twice

I am currently farming `chia` and `flax` without apparent issues, `nchain` and `hddcoin` are syncing again without apparent issues, so I believe it's just a web gui problem.

Here is my `docker-compose.yml` file that I use to start everything up (using `portainer` if it can help in some way). I removed repeated info and my username

```yaml
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris 
        container_name: machinaris 
        hostname: controller 
        restart: always 
        volumes: 
            - /home/___/.machinaris:/root/.chia 
            - "/media/___/HDD1:/HDD1" 
            - "/media/___/HDD2:/HDD2" 
            - "/media/___/HDD3:/HDD3" 
            - "/media/___/HDD4:/HDD4" 
            - "/media/___/HDD5:/HDD5" 
            - "/media/___/HDD6:/HDD6" 
            - "/media/___/HDD7:/HDD7" 
            - "/media/___/HDD8:/HDD8" 
            - "/media/___/HDD9:/HDD9" 
            - "/media/___/HDD11:/HDD11" 
            - "/media/___/HDD12:/HDD12" 
        environment: 
            - TZ=Europe/Rome
            - mode=fullnode 
            - worker_address=192.168.1.112 
            - plots_dir=/HDD1:/HDD2:/HDD3:/HDD4:/HDD5:/HDD6:/HDD7:/HDD8:/HDD9:/HDD11:/HDD12 
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447 
 
    machinaris-flax: 
        image: ghcr.io/guydavis/machinaris-flax 
        container_name: machinaris-flax 
        hostname: controller-flax 
        restart: always 
        volumes: 
            - /home/___/.machinaris-flax:/root/.chia 
            - [same hdds]
        environment: 
            - TZ=Europe/Rome 
            - mode=fullnode 
            - controller_host=[same ip]
            - worker_address=[same ip]
            - worker_api_port=8928 
            - plots_dir=[same hdds]
            - blockchains=flax 
        ports: 
            - 8928:8928 
            - 6888:6888 
            - 6885:6885 
 
    machinaris-nchain: 
        image: ghcr.io/guydavis/machinaris-nchain 
        container_name: machinaris-nchain 
        hostname: controller-nchain 
        restart: always 
        volumes: 
            - /home/___/.machinaris-nchain:/root/.chia 
            - [same hdds] 
        environment: 
            - TZ=Europe/Rome
            - mode=fullnode 
            - controller_host=[same ip]
            - worker_address=[same ip]
            - worker_api_port=8929 
            - plots_dir=[same hdds]
            - blockchains=nchain 
        ports: 
            - 8929:8929 
            - 58445:58445 
            - 38447:38447 
 
    machinaris-hddcoin: 
        image: ghcr.io/guydavis/machinaris-hddcoin 
        container_name: machinaris-hddcoin 
        hostname: controller-hddcoin 
        restart: always 
        volumes: 
            - /home/___/.machinaris-hddcoin:/root/.chia 
            - [same hdds]
        environment: 
            - TZ=Europe/Rome
            - mode=fullnode 
            - controller_host=[same ip]
            - worker_address=[same ip]
            - worker_api_port=8930 
            - plots_dir=[same hdds]
            - blockchains=hddcoin 
        ports: 
            - 8930:8930 
            - 28444:28444 
            - 28447:28447
```
