### ISSUE TITLE
Bladebit running Plot not shown in Web UI

### ISSUE THREAD

**Issue by bingemer** [guydavis/machinaris#374]
**Describe the bug**
After starting a plot with the bladebit plotter, the running job is not shown in the web ui.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Set up config with bladebit
2. Start plotter
3. No info under "Plotting", just the button shows the active plotter

**Expected behavior**
Show running job, similiar to madmax

In the container the job is showing up:
```bash
# plotman status
 plot id    plotter    k   tmp    dst   wall   phase   tmp     pid   stat       mem   user    sys   io
93c45dce   bladebit   32         /srv   0:06     1:5     0   72957    SLP   416.3Gi   3:12   0:09   0s

Total jobs: 1
Jobs in : 1

Updated at: Thu Oct 28 13:23:42 2021
```

**System setup:**
 - OS: Debian 10
 - Docker version number: 20.10.9
 - Machinaris branch: main
 - Machinaris version number: 0.6.1

**Config**
<details><summary>full configuration</summary>

```
version: "3.3"
services:

    machinaris:
        image: ghcr.io/guydavis/machinaris
        container_name: machinaris
        hostname: dl560g8
        dns: 10.0.255.1
        restart: always
        volumes:
            - ~/.machinaris:/root/.chia
            - "/mnt:/mnt"
            - "/srv:/srv"
        environment:
            - TZ=Europe/Berlin
            - farmer_pk=FARMER-KEY
            - pool_pk=POOL-KEY
            - pool_contract_address=CONTRACT-ADRESS
            - mode=fullnode
            - worker_address=x.x.x.x
            - worker_api_port=8927
            - plots_dir=/mnt/sata14tb1e:/mnt/sata14tb2e:/mnt/sata14tb3e:/mnt/sata14tb4e:/mnt/sata16tb1e:/mnt/sata16tb2e:/mnt/sata16tb3e:/mnt/sata16tb4e:/mnt/sata16tb5e:/mnt/sata16tb6e:/mnt/sata16tb7e:/mnt/sata16tb8e:/mnt/sata16tb9e:/mnt/sata16tb10e:/mnt/sata16tb11e:/mnt/sata16tb12e:/mnt/sata16tb13e:/mnt/sata16tb14e:/mnt/sata16tb15e:/mnt/sata16tb16e:/mnt/sata16tb17e:/mnt/sata16tb18e:/mnt/sata16tb19e:/mnt/sata16tb20e:/mnt/sata16tb21e:/mnt/sata3tb1e:/mnt/sata3tb2e:/mnt/usb14tb1e:/mnt/usb14tb2e:/mnt/usb14tb3e:/mnt/usb14tb4e:/mnt/usb14tb5e:/mnt/usb14tb6e:/mnt/usb14tb7e:/mnt/usb14tb8e:/mnt/usb14tb9e:/mnt/usb14tb10e:/mnt/usb14tb11e:/mnt/usb14tb12e:/mnt/usb14tb13e:/mnt/usb14tb14e:/mnt/usb14tb15e:/mnt/usb14tb16e:/srv
            - blockchains=chia
        ports:
            - 8926:8926
            - 8927:8927
```

</details>

**Additional context & screenshots**
<!-- Add any other context about the problem here, including full page screenshots. -
![Snag_66fbec1](https://user-images.githubusercontent.com/17237845/139247367-7a422361-4bb8-4cf1-84bd-8e1075435b65.png)
->
