### ISSUE TITLE
Connections view throwing warning and unable to add connections

### ISSUE THREAD

**Issue by pentacore** [guydavis/machinaris#410]
**Describe the bug**
I just upgraded from Machinaris 0.5.1 to 0.6.4, now when i go to the connections tab i get the following warnings:
`DataTables warning: table id=conns_chia-node_chia - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`
`DataTables warning: table id=conns_chia-node_flax - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3`

Also when i try to manually adding a connection to a chia or flax node i get
`Invalid connection "209.126.77.25:8444" provided. Must be HOST:PORT.`
And
`'NoneType' object has no attribute 'url'`

**To Reproduce**

- Upgraded from 0.5.1 and followed the instructions to separate the chia and flax workers
- Go to connections tab
- See warning pop-ups
- Try to add a connection to chia or flax worker, get errors.

**Expected behavior**

**System setup:**
 - OS: Ubuntu server 20.04.3 LTS
 - Docker version number: 20.10.7
 - Machinaris branch: main
 - Machinaris version number: 0.6.4

**Config**
<details><summary>full configuration</summary>

```
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:latest 
        container_name: machinaris 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris:/root/.chia 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - worker_address=192.168.1.10 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447 
 
    machinaris-cactus: 
        image: ghcr.io/guydavis/machinaris-cactus:latest 
        container_name: machinaris-cactus 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-cactus:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8936 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=cactus 
        ports: 
            - 8936:8936 
            - 11444:11444 
            - 11447:11447 
        depends_on: 
            - machinaris 
 
    machinaris-flax: 
        image: ghcr.io/guydavis/machinaris-flax:latest 
        container_name: machinaris-flax 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-flax:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8928 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=flax 
        ports: 
            - 8928:8928 
            - 6888:6888 
            - 6885:6885 
        depends_on: 
            - machinaris 
 
    machinaris-flora: 
        image: ghcr.io/guydavis/machinaris-flora:latest 
        container_name: machinaris-flora 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-flora:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8932 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=flora 
        ports: 
            - 8932:8932 
            - 18644:18644 
            - 18647:18647 
        depends_on: 
            - machinaris 
 
    machinaris-hddcoin: 
        image: ghcr.io/guydavis/machinaris-hddcoin:latest 
        container_name: machinaris-hddcoin 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-hddcoin:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8930 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=hddcoin 
        ports: 
            - 8930:8930 
            - 28444:28444 
            - 28447:28447 
        depends_on: 
            - machinaris 
 
    machinaris-nchain: 
        image: ghcr.io/guydavis/machinaris-nchain:latest 
        container_name: machinaris-nchain 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-nchain:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8929 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=nchain 
        ports: 
            - 8929:8929 
            - 58445:58445 
            - 38447:38447 
        depends_on: 
            - machinaris 
 
    machinaris-staicoin: 
        image: ghcr.io/guydavis/machinaris-staicoin:latest 
        container_name: machinaris-staicoin 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-staicoin:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8934 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=staicoin 
        ports: 
            - 8934:8934 
            - 1999:1999 
            - 1692:1692 
        depends_on: 
            - machinaris 
 
    machinaris-stor: 
        image: ghcr.io/guydavis/machinaris-stor:latest 
        container_name: machinaris-stor 
        hostname: chia-node 
        restart: always 
        volumes: 
            - /mnt/tmp/01/.machinaris-stor:/root/.chia 
            - /mnt/tmp/01/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
            - "/mnt/dst/00:/plots0" 
            - "/mnt/tmp/00:/plotting" 
            - "/mnt/dst/01:/plots1" 
            - "/mnt/dst/02:/plots2" 
        environment: 
            - TZ=Europe/Stockholm 
            - mode=fullnode 
            - controller_host=192.168.1.10 
            - worker_address=192.168.1.10 
            - worker_api_port=8935 
            - plots_dir=/plots0:/plots1:/plots2 
            - blockchains=stor 
        ports: 
            - 8935:8935 
            - 8668:8668 
            - 8337:8337 
        depends_on: 
            - machinaris 
```

</details>

**Additional context & screenshots**
