### ISSUE TITLE
Farmr feature can cause high cpu on both windows and linux

### ISSUE THREAD

**Issue by Sagittarius** [guydavis/machinaris#539]
**Reproduce:**
After I setup farmr, and startup containers, from taskmanager, I see a process dllhost.exe and MsMpEng.exe occupy high cpu:
**Linux:**
![windows](https://cdn.discordapp.com/attachments/849382899101859870/931094372756381756/unknown.png)

**Windows**
![linux](https://cdn.discordapp.com/attachments/849382899101859870/931093996703469578/unknown.png)

As the Windows screenshot show,  dllhost.exe are always creating farmr log, and writing, then close, again and again.

And on linux, we can use `lsof` to monitor, the same problem to Windows.

**Expected behavior**

**System setup:**
Windows and TrueNAS SCALE(debain)

**Config**
<details><summary>full configuration</summary>

```
version: '3.9' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:v0.6.8 
        container_name: machinaris 
        hostname: VINCENT-DESKTOP
        restart: always 
        tty: true 
        volumes: 
            - "C:/Users/Vincent/machinaris/.machinaris:/root/.chia"
            - "F:/nftplots:/plots/f"
            - "G:/nftplots:/plots/g" 
            - "H:/nftplots:/plots/h"
            - "I:/nftplots:/plots/i"
            - "J:/nftplots:/plots/j"
            - "k:/nftplots:/plots/k"
            - "N:/nftplots:/plots/n" 
            - "O:/nftplots:/plots/o" 
            - "P:/nftplots:/plots/p"
            - "Q:/nftplots:/plots/q" 
            - "R:/nftplots:/plots/r"
            - "S:/nftplots:/plots/s"
            - "T:/nftplots:/plots/t"
        environment: 
            - TZ=Asia/Shanghai 
            - farmer_address=192.168.50.62 
            - farmer_port=8447
            - mode=harvester 
            - controller_host=192.168.50.62 
            - controller_api_port=8927
            - worker_address=192.168.50.220
            - worker_api_port=8927
            - plots_dir=/plots/f:/plots/g:/plots/h:/plots/i:/plots/j:/plots/k:/plots/n:/plots/o:/plots/p:/plots/q:/plots/r:/plots/s:/plots/t
            - blockchains=chia
        ports: 
            - 8926:8926 
            - 8927:8927
```
</details>

**Additional context & screenshots**
