### ISSUE TITLE
Plotting speed graph not updating

### ISSUE THREAD

**Issue by hutchwilco** [guydavis/machinaris#584]
**Describe the bug**
Plotting Speed graph on fullnode under Plotting>Jobs tab is not updating - stuck on a week ago.

**To Reproduce**

Steps to reproduce the behavior, e.g.:
1. Use Machinaris normally (two plotters, one full node)

**Expected behavior**
Expect the graph to continue updating  to current time

**System setup:**
 - OS: Ubuntu 20.04 - on each plotter and the full node.
 - Docker version 20.10.8, build 3967b7d
 - Machinaris branch: main
 - Machinaris version number 0.6.9

**Config**
<details><summary>full configuration</summary>

```
version: '3.9'
services:
    machinaris:
        image: ghcr.io/guydavis/machinaris
        container_name: machinaris
        hostname: gridshare-ONDA-Chia-D32H-D4-V1-01
        restart: always
        volumes:
            - ~/.machinaris:/root/.chia
            - "/media/gridshare/sda:/plotsa"
            - "/media/gridshare/sdb:/plotsb"
            - "/media/gridshare/sdc:/plotsc"
            - "/media/gridshare/sdd:/plotsd"
            - "/media/gridshare/sde:/plotse"
            - "/media/gridshare/sdf:/plotsf"
            - "/media/gridshare/sdg:/plotsg"
            - "/media/gridshare/sdh:/plotsh"
            - "/media/gridshare/sdi:/plotsi"
            - "/media/gridshare/sdj:/plotsj"
            - "/media/gridshare/sdk:/plotsk"
            - "/media/gridshare/sdl:/plotsl"
            - "/media/gridshare/sdm:/plotsm"
            - "/media/gridshare/sdn:/plotsn"
            - "/media/gridshare/sdo:/plotso"
            - "/media/gridshare/sdp:/plotsp"
            - "/media/gridshare/sdq:/plotsq"
            - "/media/gridshare/sdr:/plotsr"
            - "/media/gridshare/sds:/plotss"
            - "/media/gridshare/sdt:/plotst"
            - "/media/gridshare/sdu:/plotsu"
            - "/media/gridshare/sdv:/plotsv"
            - "/media/gridshare/sdw:/plotsw"
            - "/media/gridshare/sdx:/plotsx"
            - "/media/gridshare/sdy:/plotsy"
            - "/media/gridshare/sdz:/plotsz"
            - "/media/gridshare/sdaa:/plotsaa"
            - "/media/gridshare/sdab:/plotsab"
            - "/media/gridshare/sdac:/plotsac"
            - "/media/gridshare/sdad:/plotsad"
            - "/media/gridshare/sdae:/plotsae"
            - "/media/gridshare/sdaf:/plotsaf"
        environment:
            - TZ=Pacific/Auckland
            - mode=fullnode
            - plots_dir=/plotsa:/plotsb:/plotsc:/plotsd:/plotse:/plotsf:/plotsg:/plotsh:/plotsi:/plotsj:/plotsk:/plotsl:/plotsm:/plotsn:/plotso:/plotsp:/plotsq:/plotsr:/plotss:/plotst:/plotsu:/plotsv:/plotsw:/plotsx:/plotsy:/plotsz:/plotsaa:/plotsab:/plotsac:/plotsad:/plotsae:/plotsaf
            - blockchains=chia
            - worker_address=10.0.1.96
        ports:
            - 8926:8926
            - 8927:8927
            - 8444:8444
            - 8447:8447
```

</details>

**Additional context & screenshots**
Plotting graph stuck on 17 Feb, (as at 24th Feb). Ignore the gap in plotting, that was other issues.
<img width="1561" alt="Screen Shot 2022-02-24 at 2 20 03 PM" src="https://user-images.githubusercontent.com/4792731/155438921-7a677933-b3af-49e2-bb9a-1f0a7d88e439.png">
