### ISSUE TITLE
Chiadog spamming XCH wallet recipets each time i pull a new dev build

### ISSUE THREAD

**Issue by c0rnflake** [guydavis/machinaris#588]
I pull the new dev builds each time unraid lets me know the dockers been updated, and each time i do chiadog spams my discord announce channel with XCH recipts.

this is a screen shot from this mornings pull,

![image](https://user-images.githubusercontent.com/2790597/156077123-17e8d875-4267-491e-931a-d6b24f31c152.png)

This is my current chiadog settings for xch,

```
# This is useful to differentiate multiple chiadog
# instances monitoring multiple harvesters
notification_title_prefix: 'Machinaris-Chia'
log_level: INFO

# Only one consumer can be enabled at a time, you can
# delete the section for the consumer which you aren't using
# DON'T CHANGE file_path IT'S ALREADY SET IN-CONTAINER FOR MACHINARIS!
chia_logs:
  file_log_consumer:
    enable: true
    file_path: '~/.chia/mainnet/log/debug.log'

# Enable this and chiadog will ping a remote server every 5 minutes
# That way you can know that the monitoring is running as expected
#keep_alive_monitor:
#  enable_remote_ping: false
#  ping_url: ''

# Enable this and you'll receive a daily summary notification
# on your farm performance at the specified time of the day.
daily_stats:
  enable: true
  time_of_day: 0

# We support a lot of notifiers, please check the README for more
# information. You can delete the sections which you aren't using.
# You can also enable more than one notifier and send different
# notifications to each of them. E.g. enable daily_stats only to E-mail.
# If you enable wallet_events you'll get notifications anytime your
# wallet receives some XCH (e.g. farming reward).
notifier:
  pushover:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      api_token: 'dummy_token'
      user_key: 'dummy_key'
  telegram:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      bot_token: 'dummy_bot_token'
      chat_id: 'dummy_chat_id'
  smtp:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      sender: 'chia@example.com'
      sender_name: 'chiadog'
      recipient: 'you@example.com'
      username_smtp: 'username'
      password_smtp: 'password'
      host: 'smtp.example.com'
      port: 587
  script:
    # DON'T CHANGE THIS SCRIPT NOTIFIER, IT'S USED BY MACHINARIS!
    enable: true
    daily_stats: true
    wallet_events: true
    script_path: '/root/.chia/chiadog/notifier.sh'
  discord:
    enable: true
    daily_stats: true
    wallet_events: true
    credentials:
      webhook_url: 'https://discord.com/api/webhooks/REMOVED_HOOK_AS_I_DONT_NEED_MORE_SPAM'
  slack:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
     webhook_url: 'https://hooks.slack.com/services/...'
  mqtt:
    enable: false
    daily_stats: true
    wallet_events: true
    topic: chia/chiadog/alert
    qos: 1
    retain: false
    credentials:
      host: '192.168.0.10'
      port: 8883
      username: ''
      password: ''
```
