### ISSUE TITLE
Control ports of maize and moon are the same in current (dev?) configurator

### ISSUE THREAD

**Issue by rabbitii** [guydavis/machinaris#808]
```
machinaris-maize: 
        image: ghcr.io/guydavis/machinaris-maize:test 
        container_name: machinaris-maize 
        hostname: test 
        restart: always 
        volumes: 
            - ~/.machinaris-maize:/root/.chia 
            - ~/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
        environment: 
            - TZ=Asia/Jerusalem 
            - mode=fullnode 
            - controller_host=1.1.1.1 
            - worker_address=1.1.1.1 
            - worker_api_port=8953 
            - plots_dir= 
            - blockchains=maize 
        ports: 
            - 8953:8953 
            - 8644:8644 
            - 8647:8647 
        depends_on: 
            - machinaris 

    machinaris-moon: 
        image: ghcr.io/guydavis/machinaris-moon:test 
        container_name: machinaris-moon 
        hostname: test 
        restart: always 
        volumes: 
            - ~/.machinaris-moon:/root/.chia 
            - ~/.machinaris/mnemonic.txt:/root/.chia/mnemonic.txt:ro 
        environment: 
            - TZ=Asia/Jerusalem 
            - mode=fullnode 
            - controller_host=1.1.1.1 
            - worker_address=1.1.1.1 
            - worker_api_port=8953 
            - plots_dir= 
            - blockchains=moon 
        ports: 
            - 8953:8953 
            - 26888:26888 
            - 26882:26882 
        depends_on: 
            - machinaris 
 ```
