### ISSUE TITLE
(RaspPi) chia-blockchain/venv/bin/gunicorn: No such file or directory (altcoins)

### ISSUE THREAD

**Issue by bclaasssen** [guydavis/machinaris#890]
Im running machinaris Chia with two altcoins 
Chia seems to be running fine.
In the webserver i can see all Chia stats, **but the altcoins aint visible.**
Both altcoins have 5 processes running (deamon, harvester, farmer, fullnode and wallet)
**The alt blockchain databases are a day old**, so seems even the processes are running, there not connected.

After docker compose up i get these errors:
`/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory
/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory`

Running **Ubuntu** Version 20.04.6 LTS
Armbian 23.02.2 Focal
Kernel: Linux 5.15.89-rockchip64
On rockpi-4b arm64 5.15.89-rockchip64

**docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.89-rockchip64
 Operating System: Armbian 23.02.2 Focal
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 3.773GiB
 Name: rockpi-4b
 ID: 37fbf91a-ae0c-4f52-9a10-9332ad7e296a
 Docker Root Dir: /mnt/ssd/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
````

**docker logs machinaris-greenbtc**
```
Welcome to Machinaris v0.8.8!
greenbtc - fullnode on aarch64
Sorry, GreenBTC does not offer a recent blockchain DB for download.  Standard sync will happen over a few weeks.
It is recommended to add some peer node connections on the Connections page of Machinaris.
Configuring GreenBTC...
Adding key at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1, /plots2, /plots3, /plots4, /plots5, /plots6, /plots7, /plots8, /plots9, /plots10, /plots11, /plots12, /plots13, /plots14, /plots15, /plots17, /plots18, /plots19, /plots20, /plots21, /plots22, /plots23, /plots24, /plots25, /plots26, /plots27, /plots28, /plots29, /plots30, /plots31, /plots32
Daemon not started yet
Starting daemon
greenbtc_harvester: started
greenbtc_farmer: started
greenbtc_full_node: started
greenbtc_wallet: started
Configuring Plotman...
Starting Machinaris API server...
Configuring API server for arch_name=aarch64
Starting Machinaris Web server...
Completed startup.  Browse to port 8926.
/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory
Welcome to Machinaris v0.8.8!
greenbtc - fullnode on aarch64
Configuring GreenBTC...
Adding key at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1, /plots2, /plots3, /plots4, /plots5, /plots6, /plots7, /plots8, /plots9, /plots10, /plots11, /plots12, /plots13, /plots14, /plots15, /plots17, /plots18, /plots19, /plots20, /plots21, /plots22, /plots23, /plots24, /plots25, /plots26, /plots27, /plots28, /plots29, /plots30, /plots31, /plots32
Daemon not started yet
Starting daemon
greenbtc_harvester: started
greenbtc_farmer: started
greenbtc_full_node: started
greenbtc_wallet: started
Configuring Plotman...
Starting Machinaris API server...
/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
Starting Machinaris Web server...
Completed startup.  Browse to port 8926.
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory
```
`

**docker logs machinaris-hddcoin**
`
```
Welcome to Machinaris v0.8.8!
hddcoin - fullnode on aarch64
Downloading HDDCoin blockchain DB (many GBs in size) on first launch...
Please be patient as takes minutes now, but saves days of syncing time later.
Configuring HDDCoin...
Adding key at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1, /plots2, /plots3, /plots4, /plots5, /plots6, /plots7, /plots8, /plots9, /plots10, /plots11, /plots12, /plots13, /plots14, /plots15, /plots17, /plots18, /plots19, /plots20, /plots21, /plots22, /plots23, /plots24, /plots25, /plots26, /plots27, /plots28, /plots29, /plots30, /plots31, /plots32
Daemon not started yet
Starting daemon
hddcoin_harvester: started
hddcoin_farmer: started
hddcoin_full_node: started
hddcoin_wallet: started
Configuring Plotman...
Starting Machinaris API server...
Configuring API server for arch_name=aarch64
/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
Starting Machinaris Web server...
Completed startup.  Browse to port 8926.
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory
Welcome to Machinaris v0.8.8!
hddcoin - fullnode on aarch64
Configuring HDDCoin...
Adding key at path: /root/.chia/mnemonic.txt
Adding plot directories at:  /plots1, /plots2, /plots3, /plots4, /plots5, /plots6, /plots7, /plots8, /plots9, /plots10, /plots11, /plots12, /plots13, /plots14, /plots15, /plots17, /plots18, /plots19, /plots20, /plots21, /plots22, /plots23, /plots24, /plots25, /plots26, /plots27, /plots28, /plots29, /plots30, /plots31, /plots32
Daemon not started yet
Starting daemon
hddcoin_harvester: started
hddcoin_farmer: started
hddcoin_full_node: started
hddcoin_wallet: started
Configuring Plotman...
Starting Machinaris API server...
/machinaris/scripts/start_machinaris.sh: line 65: /chia-blockchain/venv/bin/gunicorn: No such file or directory
Starting Machinaris Web server...
Completed startup.  Browse to port 8926.
/machinaris/scripts/start_machinaris.sh: line 80: /chia-blockchain/venv/bin/gunicorn: No such file or directory
```
`

**cat docker-compose.yml** 
````
version: '3.7' 
services: 
    machinaris: 
        image: ghcr.io/guydavis/machinaris:latest 
        container_name: machinaris 
        hostname: rockpi-4b 
        restart: always 
        volumes: 
            - "/mnt/ssd/chia:/root/.chia"
            - "/mnt/CF01-6TB:/plots1" 
            - "/mnt/CF02-6TB:/plots2" 
            - "/mnt/CF03-8TB:/plots3" 
            - "/mnt/CF04-8TB:/plots4" 
            - "/mnt/CF05-8TB:/plots5" 
            - "/mnt/CF06-8TB:/plots6" 
            - "/mnt/CF07-8TB:/plots7" 
            - "/mnt/CF08-8TB:/plots8" 
            - "/mnt/CF09-8TB:/plots9" 
            - "/mnt/CF10-8TB:/plots10" 
            - "/mnt/CF11-10TB:/plots11" 
            - "/mnt/CF12-6TB:/plots12" 
            - "/mnt/CF13-12TB:/plots13" 
            - "/mnt/CF14-12TB:/plots14" 
            - "/mnt/CF15-12TB:/plots15" 
            - "/mnt/CF17-14TB:/plots17" 
            - "/mnt/CF18-14TB:/plots18" 
            - "/mnt/CF19-12TB:/plots19" 
            - "/mnt/CF20-12TB:/plots20" 
            - "/mnt/CF21-12TB:/plots21" 
            - "/mnt/CF22-12TB:/plots22" 
            - "/mnt/CF23-12TB:/plots23" 
            - "/mnt/CF24-12TB:/plots24" 
            - "/mnt/CF25-12TB:/plots25" 
            - "/mnt/CF26-12TB:/plots26" 
            - "/mnt/CF27-14TB:/plots27" 
            - "/mnt/CF28-10TB:/plots28" 
            - "/mnt/CF29-10TB:/plots29" 
            - "/mnt/CF30-10TB:/plots30" 
            - "/mnt/CF31-12TB:/plots31" 
            - "/mnt/CF32-12TB:/plots32" 


        environment: 
            - TZ=Europe/Amsterdam 
            - mode=fullnode 
            - worker_address=192.168.1.152 
            - plots_dir=/plots1:/plots2:/plots3:/plots4:/plots5:/plots6:/plots7:/plots8:/plots9:/plots10:/plots11:/plots12:/plots13:/plots14:/plots15:/plots17:/plots18:/plots19:/plots20:/plots21:/plots22:/plots23:/plots24:/plots25:/plots26:/plots27:/plots28:/plots29:/plots30:/plots31:/plots32
            - blockchains=chia 
        ports: 
            - 8926:8926 
            - 8927:8927 
            - 8444:8444 
            - 8447:8447 
 
    machinaris-greenbtc: 
        image: ghcr.io/guydavis/machinaris-greenbtc:latest 
        container_name: machinaris-greenbtc 
        hostname: rockpi-4b 
        restart: always 
        volumes: 
            - "/mnt/ssd/greenbtc:/root/.chia"
            - "/mnt/ssd/chia/mnemonic.txt:/root/.chia/mnemonic.txt:ro"
            - "/mnt/CF01-6TB:/plots1" 
            - "/mnt/CF02-6TB:/plots2" 
            - "/mnt/CF03-8TB:/plots3" 
            - "/mnt/CF04-8TB:/plots4" 
            - "/mnt/CF05-8TB:/plots5" 
            - "/mnt/CF06-8TB:/plots6" 
            - "/mnt/CF07-8TB:/plots7" 
            - "/mnt/CF08-8TB:/plots8" 
            - "/mnt/CF09-8TB:/plots9" 
            - "/mnt/CF10-8TB:/plots10" 
            - "/mnt/CF11-10TB:/plots11" 
            - "/mnt/CF12-6TB:/plots12" 
            - "/mnt/CF13-12TB:/plots13" 
            - "/mnt/CF14-12TB:/plots14" 
            - "/mnt/CF15-12TB:/plots15" 
            - "/mnt/CF17-14TB:/plots17" 
            - "/mnt/CF18-14TB:/plots18" 
            - "/mnt/CF19-12TB:/plots19" 
            - "/mnt/CF20-12TB:/plots20" 
            - "/mnt/CF21-12TB:/plots21" 
            - "/mnt/CF22-12TB:/plots22" 
            - "/mnt/CF23-12TB:/plots23" 
            - "/mnt/CF24-12TB:/plots24" 
            - "/mnt/CF25-12TB:/plots25" 
            - "/mnt/CF26-12TB:/plots26" 
            - "/mnt/CF27-14TB:/plots27" 
            - "/mnt/CF28-10TB:/plots28" 
            - "/mnt/CF29-10TB:/plots29" 
            - "/mnt/CF30-10TB:/plots30" 
            - "/mnt/CF31-12TB:/plots31" 
            - "/mnt/CF32-12TB:/plots32" 
 
        environment: 
            - TZ=Europe/Amsterdam 
            - mode=fullnode 
            - controller_host=192.168.1.152 
            - worker_address=192.168.1.152 
            - worker_api_port=8955 
            - plots_dir=/plots1:/plots2:/plots3:/plots4:/plots5:/plots6:/plots7:/plots8:/plots9:/plots10:/plots11:/plots12:/plots13:/plots14:/plots15:/plots17:/plots18:/plots19:/plots20:/plots21:/plots22:/plots23:/plots24:/plots25:/plots26:/plots27:/plots28:/plots29:/plots30:/plots31:/plots32
            - blockchains=greenbtc 
            - blockchain_db_download=true 
        ports: 
            - 8955:8955 
            - 23333:23333 
            - 23332:23332 
        depends_on: 
            - machinaris 
 
    machinaris-hddcoin: 
        image: ghcr.io/guydavis/machinaris-hddcoin:latest 
        container_name: machinaris-hddcoin 
        hostname: rockpi-4b 
        restart: always 
        volumes: 
            - "/mnt/ssd/hddcoin:/root/.chia"
            - "/mnt/ssd/chia/mnemonic.txt:/root/.chia/mnemonic.txt:ro"
            - "/mnt/CF01-6TB:/plots1" 
            - "/mnt/CF02-6TB:/plots2" 
            - "/mnt/CF03-8TB:/plots3" 
            - "/mnt/CF04-8TB:/plots4" 
            - "/mnt/CF05-8TB:/plots5" 
            - "/mnt/CF06-8TB:/plots6" 
            - "/mnt/CF07-8TB:/plots7" 
            - "/mnt/CF08-8TB:/plots8" 
            - "/mnt/CF09-8TB:/plots9" 
            - "/mnt/CF10-8TB:/plots10" 
            - "/mnt/CF11-10TB:/plots11" 
            - "/mnt/CF12-6TB:/plots12" 
            - "/mnt/CF13-12TB:/plots13" 
            - "/mnt/CF14-12TB:/plots14" 
            - "/mnt/CF15-12TB:/plots15" 
            - "/mnt/CF17-14TB:/plots17" 
            - "/mnt/CF18-14TB:/plots18" 
            - "/mnt/CF19-12TB:/plots19" 
            - "/mnt/CF20-12TB:/plots20" 
            - "/mnt/CF21-12TB:/plots21" 
            - "/mnt/CF22-12TB:/plots22" 
            - "/mnt/CF23-12TB:/plots23" 
            - "/mnt/CF24-12TB:/plots24" 
            - "/mnt/CF25-12TB:/plots25" 
            - "/mnt/CF26-12TB:/plots26" 
            - "/mnt/CF27-14TB:/plots27" 
            - "/mnt/CF28-10TB:/plots28" 
            - "/mnt/CF29-10TB:/plots29" 
            - "/mnt/CF30-10TB:/plots30" 
            - "/mnt/CF31-12TB:/plots31" 
            - "/mnt/CF32-12TB:/plots32" 
 
        environment: 
            - TZ=Europe/Amsterdam 
            - mode=fullnode 
            - controller_host=192.168.1.152 
            - worker_address=192.168.1.152 
            - worker_api_port=8930 
            - plots_dir=/plots1:/plots2:/plots3:/plots4:/plots5:/plots6:/plots7:/plots8:/plots9:/plots10:/plots11:/plots12:/plots13:/plots14:/plots15:/plots17:/plots18:/plots19:/plots20:/plots21:/plots22:/plots23:/plots24:/plots25:/plots26:/plots27:/plots28:/plots29:/plots30:/plots31:/plots32 
            - blockchains=hddcoin 
            - blockchain_db_download=true 
        ports: 
            - 8930:8930 
            - 28444:28444 
            - 28447:28447 
        depends_on: 
            - machinaris 

```
